apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    env:
    - name: GREETING
      value: "Warm greetings to"
    - name: HONORIFIC
      value: "The Most Honorable"
    - name: NAME
      value: "Kubernetes"
    - name: PODVAR
      value: sEaRchFoRmE1234
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    env:
    - name: JUSTATEST
      value: "This is just a test"
    - name: NAME
      value: "Kubernetes"