apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  namespace: test
spec:
  serviceName: nginx-statefulset
  replicas: 1
  selector:
    matchLabels:
      app: nginx-statefulset
  template:
    metadata:
      labels:
        app: nginx-statefulset
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
        - name: GREETING
          value: "Warm greetings to"
        - name: NAME
          value: "Kubernetes"
        - name: STATEFULSETVAR
          value: sEaRchFoRmE1234