apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-with-data
  namespace: test
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  CONFIGMAPVAR: sEaRchFoRmE1234
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-with-data-in-file
  namespace: test
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5  
    CONFIGMAPVAR=sEaRchFoRmE1234  
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-with-data-no-match
  namespace: test
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    