apiVersion: v1
kind: Secret
metadata:
  name: secret-no-match
  namespace: test
type: Opaque
stringData:
  username: admin 
  password: t0p-Secret 
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-match-string-data
  namespace: test
type: Opaque
stringData:
  username: admin 
  password: t0p-Secret 
  SECRETVAR: sEaRchFoRmE1234
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-match-data
  namespace: test
type: Opaque
data:
  username: YWRtaW4K 
  SECRETVAR: c0VhUmNoRm9SbUUxMjM0Cg==
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-match-file-data
  namespace: test
type: Opaque
data:
  top-secrets.conf: | 
    U0VDUkVUVkFSPXNFYVJjaEZvUm1FMTIzNAo=